### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by matthieuleorat** [devgiants/docker-boilerplate-wordpress#2]
The database user does not have the permission to create the database
Log trace
Success: WordPress downloaded.
Success: Generated 'wp-config.php' file.
ERROR 1044 (42000) at line 1: Access denied for user 'user'@'%' to database 'database'
Error: Impossible de sélectionner la base données. Nous avons pu nous connecter au serveur de la base données (ce qui signifie que votre nom d’utilisateur et mot de passe sont bons), mais nous n’avons pas pu sélectionner la base de données `database`.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 62, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/main.py", line 442, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
ValueError: file descriptor cannot be a negative integer (-1)
docker-compose returned -1
Error: Impossible de sélectionner la base données. Nous avons pu nous connecter au serveur de la base données (ce qui signifie que votre nom d’utilisateur et mot de passe sont bons), mais nous n’avons pas pu sélectionner la base de données `database`.

**Comment by devgiants** [comment]
Hi,
This is fixed by 311b8cf27597e8a46cacb1c250b349522f5cdff5.
